### ISSUE TITLE
Suggestion: run plugin through clang checks

### ISSUE THREAD

**Issue by EncryptedNomad** [JonasReich/OpenUnrealUtilities#4]
This plugin fails to compile on a device that requires clang++ to pass as part of it compilation process. It also gets flagged in pipelines that integrate clang into their process.

Suggestion to run the current code through clang checks, and/or to integrate clang into the repository through Github Actions.

**Comment by JonasReich** [comment]
Hi, thanks for the suggestion!
I've had pre-1.0 versions of the plugin running in a project that was compiled for a clang based platform but not at this moment, I have not yet tried out clang cross-compilation on Windows, but I might give it a try in the next couple of weeks.

At this point I don't want to make any guarantees on clang compatibility, but I am aiming for it in the next couple months.

In the meantime, feel free to submit pull requests for any compile issue fixes.

**Comment by JonasReich** [comment]
For anyone else interested in looking into this, these wiki links might be useful to get started with Linux cross compilation:
* https://michaeljcole.github.io/wiki.unrealengine.com/Compiling_For_Linux/
* https://docs.unrealengine.com/5.0/en-US/linux-development-requirements-for-unreal-engine/

**Comment by EncryptedNomad** [comment]
Thanks for the feedback! Much appreciated, I'll see if I can get around to this myself.. once I can get a bit of breathing room from the dayjob.

**Comment by JonasReich** [comment]
I've had to make some changes to the plugin for UE5.1 and fixed most clang compilation warnings and errors I encountered along the way. You can find those changes in the commits leading up to 80a6100029d42c8e4d7e364d8dda10d727dfd088
